//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatterbox.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarmentImage
    {
        public System.Guid Id { get; set; }
        public int GarmentId { get; set; }
        public string Notes { get; set; }
        public byte[] Image { get; set; }
        public string ConentType { get; set; }
        public string FileName { get; set; }
        public long FileSize { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Garment Garment { get; set; }
    }
}
